Repository baidu/openedge, pull requests merged in 2019-03, with the labels that each got.

#127 refactor function manager: remove keep order, add retry, add test
  Makefile
  openedge-function-manager/config.go
  openedge-function-manager/dispatcher.go
  openedge-function-manager/factory.go
  openedge-function-manager/function.go
  openedge-function-manager/function_test.go
  openedge-function-manager/instance.go
  openedge-function-manager/ruler.go
  openedge-function-python27/function_pb2.py
  openedge-remote-mqtt/config_test.go
  protocol/mqtt/config.go
  sdk-go/openedge/function.pb.go
  sdk-go/openedge/function.proto
Labels: enhancement

#132 remove tools; remove console config in logger; change system update api
  Makefile
  doc/us-en/tutorials/Config-interpretation.md
  doc/zh-cn/tutorials/Config-interpretation.md
  example/docker/var/db/openedge/agent-conf/service.yml
  example/docker/var/db/openedge/function-manager-conf/service.yml
  example/docker/var/db/openedge/localhub-conf/service.yml
  example/docker/var/db/openedge/remote-iothub-conf/service.yml
  example/native/var/db/openedge/agent-conf/service.yml
  example/native/var/db/openedge/function-manager-conf/service.yml
  example/native/var/db/openedge/localhub-conf/service.yml
  example/native/var/db/openedge/remote-iothub-conf/service.yml
  logger/config.go
  logger/logger.go
  master/api/server.go
  master/update.go
  master/update_unix_test.go
  openedge-agent/config.go
  openedge-agent/download.go
  openedge-agent/event.go
  openedge-agent/main.go
  openedge-function-manager/config.go
  openedge-hub/config/subscription.go
  openedge-hub/rule/manager_test.go
  openedge-hub/rule/ruletopic_test.go
  protocol/mqtt/config.go
  sdk-go/openedge/client.go
  sdk-go/openedge/config.go
  sdk-go/openedge/context.go
  tools/openedge-consistency/main.go
  tools/pubsub/main.go
  tools/pubsub/perf.go
  tools/pubsub/pub.go
  tools/pubsub/sub.go
  tools/test/docker_client_test.go
Labels: bug

#133 bugfixes
  cmd/start.go
  example/docker/var/db/openedge/application.yml
  example/docker/var/db/openedge/function-filter-conf/service.yml
  example/docker/var/db/openedge/function-manager-conf/service.yml
  example/native/var/db/openedge/application.yml
  example/native/var/db/openedge/function-filter-conf/service.yml
  example/native/var/db/openedge/function-manager-conf/service.yml
  openedge-function-python27/openedge-function-python27.py
  sdk-go/openedge/client.go
  sdk-go/openedge/config.go
  sdk-go/openedge/context.go
  sdk-go/openedge/function_server.go
Labels: bug

#135 hub module update about tls and auth
  example/docker/var/db/openedge/application.yml
  example/docker/var/db/openedge/localhub-cert-only-for-test/ca.pem
  example/docker/var/db/openedge/localhub-cert-only-for-test/server.key
  example/docker/var/db/openedge/localhub-cert-only-for-test/server.pem
  example/docker/var/db/openedge/localhub-conf/service.yml
  example/native/var/db/openedge/application.yml
  example/native/var/db/openedge/localhub-cert-only-for-test/ca.pem
  example/native/var/db/openedge/localhub-cert-only-for-test/server.key
  example/native/var/db/openedge/localhub-cert-only-for-test/server.pem
  example/native/var/db/openedge/localhub-conf/service.yml
  openedge-hub/auth/auth.go
  openedge-hub/auth/auth_test.go
  openedge-hub/config/auth.go
  openedge-hub/config/config.go
  openedge-hub/config/config_test.go
  openedge-hub/server/manager_test.go
  openedge-hub/server/testcert/ca.pem
  openedge-hub/server/testcert/server.key
  openedge-hub/server/testcert/server.pem
  openedge-hub/server/testcert/testssl2.key
  openedge-hub/server/testcert/testssl2.pem
  openedge-hub/session/session_handle.go
  openedge-hub/session/session_ingress.go
  openedge-hub/session/session_test.go
  protocol/mqtt/utils.go
Labels: bug

#136 add state of instances in native process mode
  master/engine/docker/instance.go
  master/engine/docker/service.go
  master/engine/native/instance.go
  master/engine/native/service.go
  master/engine/supervisor.go
  openedge-function-manager/function.go
  openedge-function-manager/function_test.go
  openedge-function-manager/instance.go
Labels: enhancement

#138 update agent logic
  example/docker/var/db/openedge/agent-conf/service.yml
  example/docker/var/db/openedge/function-filter-conf/service.yml
  example/docker/var/db/openedge/function-manager-conf/service.yml
  example/docker/var/db/openedge/function-sayhi-conf/service.yml
  example/docker/var/db/openedge/localhub-conf/service.yml
  example/native/var/db/openedge/agent-conf/service.yml
  master/api/server.go
  master/master.go
  master/service.go
  master/testdata/var/db/openedge/app/v1/application.yml
  master/testdata/var/db/openedge/app/v2/application.yml
  master/testdata/var/db/openedge/app/v3/application.yml
  master/testdata/var/db/openedge/app/v5/application.yml
  master/testdata/var/db/openedge/app/v6/application.yml
  master/update.go
  master/update_test.go
  openedge-agent/config.go
  openedge-agent/download.go
  openedge-agent/event.go
  openedge-agent/event_test.go
  openedge-agent/main.go
  openedge-function-manager/function_test.go
  sdk/openedge-go/client.go
  sdk/openedge-go/config.go
  sdk/openedge-go/config_test.go
  sdk/openedge-go/context.go
  utils/path.go
Labels: bug

#141 bugfix of agent module
  example/docker/var/db/openedge/agent-conf/service.yml
  example/native/var/db/openedge/agent-conf/service.yml
  master/update.go
  openedge-agent/config.go
  openedge-agent/download.go
  openedge-agent/main.go
  protocol/http/client.go
  protocol/http/client_test.go
  protocol/http/server.go
  vendor/github.com/baidubce/bce-sdk-go/LICENSE
  vendor/github.com/baidubce/bce-sdk-go/http/client.go
  vendor/github.com/baidubce/bce-sdk-go/http/constants.go
  vendor/github.com/baidubce/bce-sdk-go/http/request.go
  vendor/github.com/baidubce/bce-sdk-go/http/response.go
  vendor/github.com/baidubce/bce-sdk-go/util/string.go
  vendor/github.com/baidubce/bce-sdk-go/util/time.go
  vendor/vendor.json
Labels: bug

#142 support to specify devices that will be accessible within the service container
  master/engine/docker/engine.go
  sdk/openedge-go/config.go
Labels: enhancement

#146 bugfixes: sock file is not mapped and image cannot be pulled in docker mode
  doc/images/overview/design/openedge_design.png
  master/engine/docker/container.go
  master/engine/docker/engine.go
  master/master.go
  master/update.go
  sdk/openedge-go/context.go
  utils/path_test.go
Labels: P0, bug

#153 bugfix: support to config multiple functions and env on faas
  master/engine/docker/service.go
  master/engine/native/service.go
  openedge-function-manager/instance.go
Labels: bug

#158 bugfix: change max length of volume name from 32 to 64
  master/engine/native/process.go
  sdk/openedge-go/config.go
  sdk/openedge-go/config_test.go
Labels: bug

#162 use serial number to find right cert after cert rotation
  openedge-agent/config.go
  openedge-agent/main.go
  utils/cert.go
  utils/cert_test.go
Labels: bug
