Repository baidu/openedge, pull requests merged in 2019-04, with the labels that each got.

#164 update docs for openedge 0.1.2
  doc/images/tutorials/process/openedge-docker-ps-after.png
  doc/images/tutorials/process/openedge-docker-ps-python-start.png
  doc/images/tutorials/process/openedge-function-start.png
  doc/images/tutorials/process/openedge-python-start.png
  doc/us-en/customize/How-to-write-a-python-script-for-python-runtime.md
  doc/us-en/tutorials/Message-handling-with-function-module.md
  doc/us-en/tutorials/Message-transfer-among-devices-with-hub-module.md
  doc/zh-cn/customize/How-to-write-a-python-script-for-python-runtime.md
  doc/zh-cn/tutorials/Message-handling-with-function-module.md
  doc/zh-cn/tutorials/Message-transfer-among-devices-with-hub-module.md
Labels: good first issue

#163 update openedge doc to version 0.1.2
  .gitignore
  Makefile
  cmd/start.go
  cmd/version.go
  doc/images/overview/design/function.png
  doc/images/overview/design/hub.png
  doc/images/overview/design/mode_docker.png
  doc/images/overview/design/mode_native.png
  doc/images/overview/design/openedge_function.png
  doc/images/overview/design/openedge_remote_mqtt.png
  doc/images/overview/design/openedge_update.png
  doc/images/overview/design/reload.png
  doc/images/overview/design/remote.png
  doc/us-en/customize/How-to-develop-a-customize-module-for-OpenEdge.md
  doc/us-en/customize/How-to-develop-a-customize-runtime-for-function.md
  doc/us-en/overview/OpenEdge-design.md
  doc/us-en/tutorials/Config-interpretation.md
  doc/zh-cn/customize/How-to-develop-a-customize-module-for-OpenEdge.md
  doc/zh-cn/customize/How-to-develop-a-customize-runtime-for-function.md
  doc/zh-cn/overview/OpenEdge-design.md
  doc/zh-cn/tutorials/Config-interpretation.md
  example/docker/var/db/openedge/agent-conf/service.yml
  example/docker/var/db/openedge/remote-iothub-conf/service.yml
  example/native/var/db/openedge/agent-conf/service.yml
  example/native/var/db/openedge/function-filter-conf/service.yml
  example/native/var/db/openedge/function-manager-conf/service.yml
  example/native/var/db/openedge/function-sayhi-conf/service.yml
  example/native/var/db/openedge/localhub-conf/service.yml
  example/native/var/db/openedge/remote-iothub-conf/service.yml
  main.go
  master/inspect.go
  master/master.go
  openedge-agent/main.go
  openedge-function-manager/config.go
  openedge-function-manager/main.go
  openedge-hub/main.go
  openedge-remote-mqtt/main.go
  openedge-timer/Dockerfile
  openedge-timer/Makefile
  openedge-timer/main.go
  openedge-timer/package.yml
  protocol/http/config.go
  protocol/http/server.go
  protocol/mqtt/dispatcher.go
  sdk/openedge-go/config.go
  sdk/openedge-go/context.go
  sdk/openedge-go/inspect.go
  sdk/openedge-go/service.go
Labels: good first issue

#184 bugfix: system environmental variable not removed for dynamic instance
  master/engine/docker/service.go
  master/engine/native/service.go
Labels: bug

#199 master supports to report custom stats by services; add status report for hub module
  doc/us-en/customize/How-to-develop-a-customize-module-for-OpenEdge.md
  doc/zh-cn/customize/How-to-develop-a-customize-module-for-OpenEdge.md
  master/api/server.go
  master/engine/docker/container.go
  master/engine/docker/instance.go
  master/engine/docker/service.go
  master/engine/engine.go
  master/engine/instance.go
  master/engine/native/engine.go
  master/engine/native/instance.go
  master/engine/native/service.go
  master/engine/service.go
  master/inspect.go
  master/master.go
  master/service.go
  master/testdata/var/db/openedge/app/v2/application.yml
  master/update.go
  master/update_test.go
  openedge-function-manager/function_test.go
  openedge-function-manager/instance.go
  openedge-function-python27/openedge-function-python27.py
  openedge-hub/broker/broker.go
  openedge-hub/broker/broker_bg.go
  openedge-hub/config/config.go
  openedge-hub/config/config_test.go
  openedge-hub/main.go
  openedge-hub/rule/manager.go
  openedge-hub/rule/manager_test.go
  openedge-hub/rule/rule.go
  openedge-hub/rule/ruletopic_test.go
  openedge-hub/session/session_test.go
  sdk/openedge-go/client.go
  sdk/openedge-go/context.go
  sdk/openedge-go/inspect.go
  vendor/github.com/jolestar/go-commons-pool/pool.go
Labels: enhancement

#200 report volume information
  doc/us-en/overview/OpenEdge-design.md
  doc/zh-cn/overview/OpenEdge-design.md
  master/engine/docker/container.go
  master/inspect.go
  sdk/openedge-go/config.go
  sdk/openedge-go/inspect.go
Labels: enhancement

#201 stop the function instance if it cannot be returned to pool
  openedge-function-manager/function.go
  openedge-function-manager/ruler.go
  vendor/github.com/jolestar/go-commons-pool/concurrent/cond.go
Labels: bug

#203 Use exe instead of name to check the process
  master/engine/native/history.go
Labels: enhancement

#209 clean up old instances if exists when openedge starts
  master/engine/docker/container.go
  master/engine/docker/engine.go
  master/engine/docker/instance.go
  master/engine/infostats.go
  master/engine/instance.go
  master/engine/native/engine.go
  master/engine/native/instance.go
  master/engine/supervisor.go
  master/inspect.go
Labels: enhancement

#211 add module openedge-function-python36 provides the Python36 function runtime
  Makefile
  example/docker/var/db/openedge/application.yml
  example/docker/var/db/openedge/function-manager-conf/service.yml
  example/docker/var/db/openedge/function-sayhi-code/sayhi.py
  example/docker/var/db/openedge/function-sayhi-conf/service.yml
  example/native/var/db/openedge/application.yml
  example/native/var/db/openedge/function-manager-conf/service.yml
  example/native/var/db/openedge/function-sayhi-code/sayhi.py
  example/native/var/db/openedge/function-sayhi-conf/service.yml
  openedge-function-python36/.gitignore
  openedge-function-python36/Dockerfile
  openedge-function-python36/Makefile
  openedge-function-python36/function_pb2.py
  openedge-function-python36/function_pb2_grpc.py
  openedge-function-python36/manifest.yml.template
  openedge-function-python36/openedge-function-python36.py
  openedge-function-python36/package.yml
Labels: enhancement

#213 add report api doc
  cmd/start.go
  doc/us-en/overview/OpenEdge-design.md
  doc/zh-cn/overview/OpenEdge-design.md
  sdk/openedge-go/context.go
Labels: enhancement, good first issue

#215 upgrade api version to v1 and keep old version
  doc/us-en/overview/OpenEdge-design.md
  doc/zh-cn/overview/OpenEdge-design.md
  master/api/server.go
  master/engine/docker/engine.go
  master/engine/native/engine.go
  master/inspect.go
  sdk/openedge-go/client.go
  utils/stat.go
Labels: bug

#216 update doc of master api
  doc/us-en/overview/OpenEdge-design.md
  doc/zh-cn/overview/OpenEdge-design.md
Labels: good first issue

#222 support runtime for docker container mode
  master/engine/docker/engine.go
  sdk/openedge-go/config.go
Labels: enhancement
